<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260727192730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description TEXT NOT NULL, condition_type VARCHAR(50) NOT NULL, condition_valeur NUMERIC(10, 2) NOT NULL, icone VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) NOT NULL, type VARCHAR(20) NOT NULL, objectif_valeur NUMERIC(10, 2) NOT NULL, unite VARCHAR(20) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_limite DATE DEFAULT NULL, statut VARCHAR(20) NOT NULL, owner_id INT NOT NULL, sport_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D70989517E3C61F9 ON challenge (owner_id)');
        $this->addSql('CREATE INDEX IDX_D7098951AC78BCF8 ON challenge (sport_id)');
        $this->addSql('CREATE TABLE progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valeur NUMERIC(10, 2) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT DEFAULT NULL, challenge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2201F24698A21AC6 ON progress (challenge_id)');
        $this->addSql('CREATE TABLE sport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, categorie VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, pseudo VARCHAR(50) NOT NULL, avatar_url VARCHAR(255) DEFAULT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, niveau INT NOT NULL, xp_total INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_deblocage TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, badge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1C32B3457E3C61F9 ON user_badge (owner_id)');
        $this->addSql('CREATE INDEX IDX_1C32B345F7A2C2FC ON user_badge (badge_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_badge ON user_badge (owner_id, badge_id)');
        $this->addSql('ALTER TABLE challenge ADD CONSTRAINT FK_D70989517E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE challenge ADD CONSTRAINT FK_D7098951AC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id)');
        $this->addSql('ALTER TABLE progress ADD CONSTRAINT FK_2201F24698A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B3457E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_badge ADD CONSTRAINT FK_1C32B345F7A2C2FC FOREIGN KEY (badge_id) REFERENCES badge (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE challenge DROP CONSTRAINT FK_D70989517E3C61F9');
        $this->addSql('ALTER TABLE challenge DROP CONSTRAINT FK_D7098951AC78BCF8');
        $this->addSql('ALTER TABLE progress DROP CONSTRAINT FK_2201F24698A21AC6');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B3457E3C61F9');
        $this->addSql('ALTER TABLE user_badge DROP CONSTRAINT FK_1C32B345F7A2C2FC');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE progress');
        $this->addSql('DROP TABLE sport');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_badge');
    }
}
